name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm ci
          chmod +x ./node_modules/.bin/* || true

      - name: Run Cypress tests
        run: npm run cy:full

      - name: Set timestamp
        id: vars
        run: echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Upload Cypress Reports
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports-${{ env.timestamp }}
          path: |
            cypress/reports/*.html
            cypress/reports/*.json
